[2025-04-30T20:04:38.447+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-30T20:04:38.457+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retrain_on_drift.push_pipeline_metrics manual__2025-04-30T20:03:33.245974+00:00 [queued]>
[2025-04-30T20:04:38.461+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retrain_on_drift.push_pipeline_metrics manual__2025-04-30T20:03:33.245974+00:00 [queued]>
[2025-04-30T20:04:38.461+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-30T20:04:38.467+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): push_pipeline_metrics> on 2025-04-30 20:03:33.245974+00:00
[2025-04-30T20:04:38.487+0000] {standard_task_runner.py:72} INFO - Started process 967 to run task
[2025-04-30T20:04:38.490+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'retrain_on_drift', 'push_pipeline_metrics', 'manual__2025-04-30T20:03:33.245974+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/drift_retrain_dag.py', '--cfg-path', '/tmp/tmpwkmgsso4']
[2025-04-30T20:04:38.492+0000] {standard_task_runner.py:105} INFO - Job 251: Subtask push_pipeline_metrics
[2025-04-30T20:04:38.539+0000] {task_command.py:467} INFO - Running <TaskInstance: retrain_on_drift.push_pipeline_metrics manual__2025-04-30T20:03:33.245974+00:00 [running]> on host 3ca66a66642a
[2025-04-30T20:04:38.588+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='retrain_on_drift' AIRFLOW_CTX_TASK_ID='push_pipeline_metrics' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T20:03:33.245974+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T20:03:33.245974+00:00'
[2025-04-30T20:04:38.589+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-30T20:04:38.589+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-30T20:04:38.589+0000] {logging_mixin.py:190} INFO - Current task name:push_pipeline_metrics state:running start_date:2025-04-30 20:04:38.457998+00:00
[2025-04-30T20:04:38.590+0000] {logging_mixin.py:190} INFO - Dag name:retrain_on_drift and current dag run status:running
[2025-04-30T20:04:38.590+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-30T20:04:38.591+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/drift_retrain_dag.py", line 110, in _push_pipeline_metrics
    end_ts   = dr.end_date.timestamp()
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'timestamp'
[2025-04-30T20:04:38.600+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-30T20:04:38.600+0000] {logging_mixin.py:190} INFO - Task start:2025-04-30 20:04:38.457998+00:00 end:2025-04-30 20:04:38.599786+00:00 duration:0.141788
[2025-04-30T20:04:38.600+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): push_pipeline_metrics> dag:<DAG: retrain_on_drift> dagrun:<DagRun retrain_on_drift @ 2025-04-30 20:03:33.245974+00:00: manual__2025-04-30T20:03:33.245974+00:00, state:running, queued_at: 2025-04-30 20:03:33.283814+00:00. externally triggered: True>
[2025-04-30T20:04:38.600+0000] {logging_mixin.py:190} INFO - Failure caused by 'NoneType' object has no attribute 'timestamp'
[2025-04-30T20:04:38.600+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=retrain_on_drift, task_id=push_pipeline_metrics, run_id=manual__2025-04-30T20:03:33.245974+00:00, execution_date=20250430T200333, start_date=20250430T200438, end_date=20250430T200438
[2025-04-30T20:04:38.607+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-30T20:04:38.607+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 251 for task push_pipeline_metrics ('NoneType' object has no attribute 'timestamp'; 967)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/drift_retrain_dag.py", line 110, in _push_pipeline_metrics
    end_ts   = dr.end_date.timestamp()
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'timestamp'
[2025-04-30T20:04:38.633+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-30T20:04:38.645+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-30T20:04:38.646+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
